#!/bin/bash
#
# Downloads and replaces local config with config found on the node
#
source .syncconfig
JWT=${JWT/[Aa]uthorization:/}
curl -fso config.zip -H "Accept: application/zip" -H "Authorization: $JWT" "https://$NODE/api/config"
if [ $? -ne 0 ]
then
   echo "Failed to download config from the node. Maybe the JWT has expired?"
   exit 1
fi
rm -f *.conf.json
rm -f pipes/*.conf.json
rm -f systems/*.conf.json
unzip -qo config.zip
rm config.zip
echo "Local config replaced by node config."
